"""empty message

Revision ID: 28db8b1db4b8
Revises: a11283937150
Create Date: 2025-03-29 07:59:12.431462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28db8b1db4b8'
down_revision = 'a11283937150'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='usuario_pk')
    )
    # ### end Alembic commands ###
